// Fetches generalized geology from Macrostrat over a Somalia grid and generates
// supabase/migrations/0072_load_macrostrat_geology.sql. Each land grid cell becomes
// a geo.geological_layer polygon (lithology + age), so geo.geology_at (ST_Intersects)
// returns the rock unit under a sample. Source: Macrostrat / CGMW (CC-BY 4.0).
const fs = require("fs");
const path = require("path");

const STEP = 0.5;                 // grid spacing (deg) — matches the generalized source
const HALF = STEP / 2;
const LAT0 = -1.5, LAT1 = 12.0;   // Somalia bbox (+ a little border context)
const LNG0 = 41.0, LNG1 = 51.5;
const CONCURRENCY = 5;

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const jb = (o) => q(JSON.stringify(Object.fromEntries(Object.entries(o).filter(([, v]) => v != null && v !== "")))) + "::jsonb";

async function unitAt(lat, lng) {
  try {
    const r = await fetch(`https://macrostrat.org/api/v2/geologic_units/map?lat=${lat}&lng=${lng}`, { headers: { "User-Agent": "luulscan-geocontext-loader" } });
    if (!r.ok) return null;
    const j = await r.json();
    const data = j?.success?.data;
    if (!Array.isArray(data) || data.length === 0) return null;
    // First unit with a usable lithology (data[0] is the most detailed source).
    const u = data.find((d) => d.lith && d.lith.trim()) || data[0];
    if (!u || !(u.name || u.lith)) return null;
    return {
      name: (u.name && u.name.trim()) || u.lith,
      kind: u.lith || "lithology",
      attrs: { age_top_ma: u.t_age, age_bottom_ma: u.b_age, interval: u.best_int_name || u.t_int_name,
        macrostrat_map_id: u.map_id, macrostrat_source_id: u.source_id, color: u.color },
    };
  } catch { return null; }
}

(async () => {
  const points = [];
  for (let lat = LAT0; lat <= LAT1 + 1e-9; lat += STEP)
    for (let lng = LNG0; lng <= LNG1 + 1e-9; lng += STEP)
      points.push({ lat: +lat.toFixed(3), lng: +lng.toFixed(3) });

  console.log(`querying ${points.length} grid points (step ${STEP}°)…`);
  const cells = [];
  let done = 0, empty = 0;
  for (let i = 0; i < points.length; i += CONCURRENCY) {
    const batch = points.slice(i, i + CONCURRENCY);
    const res = await Promise.all(batch.map(async (p) => ({ p, u: await unitAt(p.lat, p.lng) })));
    for (const { p, u } of res) {
      done++;
      if (!u) { empty++; continue; }
      cells.push({ ...p, ...u });
    }
    if (done % 50 === 0) console.log(`  ${done}/${points.length} (${cells.length} land cells)`);
  }
  console.log(`done: ${cells.length} land cells, ${empty} empty (ocean/no-data)`);
  if (cells.length === 0) { console.error("NO DATA — aborting"); process.exit(1); }

  const values = cells.map((c) =>
    `  (${q(c.name)}, ${q(c.kind)}, ${c.lng - HALF}, ${c.lat - HALF}, ${c.lng + HALF}, ${c.lat + HALF}, ${jb(c.attrs)})`
  ).join(",\n");

  const sql = `-- 0072_load_macrostrat_geology.sql
--
-- Sprint 4.3 data load — generalized bedrock geology over Somalia from Macrostrat
-- (CGMW "Generalized geology of the world", CC-BY 4.0). ${cells.length} grid cells
-- (${STEP}° ≈ ${Math.round(STEP * 111)} km) loaded into geo.geological_layer as polygons, so
-- geo.geology_at (ST_Intersects) returns the rock unit + age under a sample — giving
-- the GeoContext \`geology\` provider real lithology/host-rock context beyond vision.
--
-- Idempotent: dataset registered once; cells replaced for this source on reload.
-- Generated by scripts/gen_macrostrat_geology.cjs — do not hand-edit.

insert into geo.dataset_registry (source_key, title, category, version, crs, license, source_url, record_count, metadata)
select 'macrostrat_cgmw', 'Macrostrat generalized geology — Somalia', 'spatial', '2026.07', 'EPSG:4326',
       'CC-BY 4.0', 'https://macrostrat.org/', ${cells.length}, '{"grid_step_deg":${STEP}}'::jsonb
where not exists (select 1 from geo.dataset_registry where source_key = 'macrostrat_cgmw' and version = '2026.07');

-- Reload-safe: clear any previous cells from this source before inserting.
delete from geo.geological_layer where source = 'Macrostrat (CGMW)';

insert into geo.geological_layer (name, kind, geom, source, attributes)
select v.name, v.kind,
       extensions.st_makeenvelope(v.xmin, v.ymin, v.xmax, v.ymax, 4326), 'Macrostrat (CGMW)', v.attrs
from (values
${values}
) as v(name, kind, xmin, ymin, xmax, ymax, attrs);

-- ── VERIFY ── expect ${cells.length} cells; a Somalia point returns a unit ──
--   select count(*) from geo.geological_layer where source='Macrostrat (CGMW)';
--   select name, kind from geo.geology_at(2.48, 43.67);   -- Archean basement (Bur region)
--   select name, kind from geo.geology_at(9.5, 45.0);     -- Cenozoic sedimentary (north)

-- ── ROLLBACK ──
--   delete from geo.geological_layer where source='Macrostrat (CGMW)';
--   delete from geo.dataset_registry where source_key='macrostrat_cgmw';
`;
  fs.writeFileSync(path.join(__dirname, "..", "supabase/migrations/0072_load_macrostrat_geology.sql"), sql);
  console.log(`wrote migration with ${cells.length} cells`);
  console.log("sample cells:", cells.slice(0, 3).map((c) => `${c.name} (${c.kind}) @${c.lat},${c.lng}`).join(" | "));
})();
