-- 0071_load_mrds_somalia.sql
--
-- Sprint 4.3 data load — USGS MRDS (Mineral Resources Data System), Somalia subset.
-- 159 real mineral occurrences (of 159 records; 0 skipped for
-- missing/invalid coordinates or deletion). Public domain (USGS). Loaded into
-- geo.mineral_occurrence so the GeoContext `occurrence` + `mineral_association`
-- providers return real spatial evidence — moving assessments beyond vision-only.
--
-- Idempotent: dataset registered once (source_key+version), occurrences deduped on
-- (dataset, external_id/MRDS dep_id). Generated from mrds-fSO.dbf by
-- scripts/gen_mrds_migration.cjs — do not hand-edit.

-- 1) Register the dataset version.
insert into geo.dataset_registry (source_key, title, category, version, crs, license, source_url, record_count, metadata)
select 'usgs_mrds', 'USGS MRDS — Somalia', 'spatial', '2026.07', 'EPSG:4326',
       'Public domain (USGS)', 'https://mrdata.usgs.gov/mrds/', 159, '{}'::jsonb
where not exists (select 1 from geo.dataset_registry where source_key = 'usgs_mrds' and version = '2026.07');

-- 2) Register the source document (lineage).
insert into geo.knowledge_source (dataset_id, source_type, title, organization, language, uri, reference)
select d.id, 'database', 'USGS Mineral Resources Data System (MRDS) — Somalia subset', 'USGS', 'en',
       'https://mrdata.usgs.gov/mrds/', 'USGS MRDS'
from geo.dataset_registry d
where d.source_key = 'usgs_mrds' and d.version = '2026.07'
  and not exists (select 1 from geo.knowledge_source ks where ks.dataset_id = d.id
                  and ks.title like 'USGS Mineral Resources Data System%');

-- 3) Load occurrences (deduped on MRDS dep_id).
insert into geo.mineral_occurrence
  (dataset_id, source_id, external_id, parser, extraction_version, name, geom, status,
   commodity_key, commodities, deposit_type, host_rocks, tier, reference, metadata)
select d.id, ks.id, v.external_id, 'mrds-dbf', '1', v.name,
       extensions.st_setsrid(extensions.st_makepoint(v.lng, v.lat), 4326), v.status,
       v.commodity_key, v.commodities, v.deposit_type, v.host_rocks, 'mapped', v.reference, v.metadata
from (values
  ('10011781', 'Arargob Prospect', 11.333860, 49.984330, 'occurrence', null, '{}'::text[], 'Replacement', array['Limestone'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83P.AZZAROLI, A., AND FOIS, V., 1964, GEOLOGICAL OUTLINES OF THE NORTHERN END OF THE HORN', '{"mrds_id":"D006906","dev_stat":"Occurrence","ore":"Barite, Galena","structure":"N43w","tectonic":"Margin, Gulf Of Aden Spreading Center","hrock_unit":"Tisje Formation","prod_size":"N","commod3":"Barium-Barite, Lead","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011781"}'::jsonb),
  ('10011783', 'Bur Galan Prospect', 2.568030, 43.451090, 'occurrence', null, '{}'::text[], null, array['Quartzite'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY- SOMALIA: UNITED NATIONS REPORT, 133 P.HOLMES, R. J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND), U. S. TECHNICAL ASSISTANCE MISS', '{"mrds_id":"D006909","dev_stat":"Occurrence","structure":"N70w","tectonic":"Precambrian Shield","prod_size":"N","commod3":"Iron","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011783"}'::jsonb),
  ('10011784', 'Culi-Culi Prospect', 2.318050, 43.501090, 'occurrence', null, '{}'::text[], null, array['Quartzite'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006910","dev_stat":"Occurrence","ore":"Hematite, Magnetite","structure":"E-W","tectonic":"Precambrian Shield","prod_size":"N","commod3":"Iron","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011784"}'::jsonb),
  ('10011785', 'Dananjieh Prospect', 10.233970, 45.034410, 'occurrence', null, '{}'::text[], null, array['Schist'], 'HUNT, J.A., 1960, GEOLOGY OF THE BERBERA-SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P.UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY-SOMALIA: UNITED NATIONS REP', '{"mrds_id":"D006912","dev_stat":"Occurrence","ore":"Barite, Fluorite, Galena","structure":"N 70 W","tectonic":"Margin Gulf Of Aden Spreading Center","prod_size":"N","commod3":"Barium-Barite, Fluorine-Fluorite, Lead","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011785"}'::jsonb),
  ('10011786', 'Darreh Hos Prospect', 9.984000, 44.917750, 'past_producer', null, '{}'::text[], null, array['Pegmatite'], 'HUNT, J.A., 1958, GEOLOGY OF THE ADADLEH AREA, HARGEISA AND BERBERA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 2, 16 P', '{"mrds_id":"D006913","dev_stat":"Past Producer","ore":"Beryl, Columbite, Muscovite","prod_size":"S","commod2":"Niobium (Columbium), Beryllium","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011786"}'::jsonb),
  ('10011787', 'El Bur Mine', 4.767820, 46.534370, 'mine', null, '{}'::text[], null, array['Limestone'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P.UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY-SOMALIA:UN', '{"mrds_id":"D006914","dev_stat":"Producer","ore":"Sepiolite","prod_size":"S","commod2":"Clay","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011787"}'::jsonb),
  ('10011788', 'Fulanful Prospect', 10.200650, 45.134410, 'occurrence', null, '{}'::text[], null, array['Limestone'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY-SOMALIA: UNITED NATIONS REPORT, 133 P.HUNT, J.A., 1960, GEOLOGY OF THE BERBERA-SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27', '{"mrds_id":"D006915","dev_stat":"Occurrence","ore":"Chalcopyrite, Galena, Pyrite","prod_size":"N","commod3":"Lead, Copper, Iron","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011788"}'::jsonb),
  ('10011790', 'Jessoma Prospect', 4.051220, 45.767730, 'occurrence', null, '{}'::text[], null, array['Sandstone'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006918","dev_stat":"Occurrence","ore":"Hematite","hrock_unit":"Jesomma Sandstone","prod_size":"N","commod3":"Iron","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011790"}'::jsonb),
  ('10011791', 'Hudiso Prospect', 10.033990, 45.201080, 'occurrence', null, '{}'::text[], null, array['Schist'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY-SOMALIA: UNITED NATIONS REPORT, 133PHUNT, J.A., 1960, GEOLOGY OF THE BERBERA-SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO.', '{"mrds_id":"D006920","dev_stat":"Occurrence","ore":"Garnet, Kyanite, Rhodonite","prod_size":"N","commod3":"Garnet, Manganese, Kyanite","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011791"}'::jsonb),
  ('10011792', 'Manja Vihin Magiaian Mine', 11.083880, 49.017690, 'occurrence', 'Tin', array['Tin'], null, array['Gneiss'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83P', '{"mrds_id":"D006921","dev_stat":"Occurrence","ore":"Cassiterite","structure":"E-W","prod_size":"N","commod2":"Tungsten, Tantalum, Niobium (Columbium)","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011792"}'::jsonb),
  ('10011793', 'Tomassah Occurrence', 11.383850, 49.917670, 'occurrence', null, '{}'::text[], null, array['Limestone'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006924","dev_stat":"Occurrence","ore":"Hematite","tectonic":"Margin Gulf Of Aden Spreading Center","prod_size":"N","commod3":"Iron","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011793"}'::jsonb),
  ('10011794', 'Wiget Prospect', 10.100660, 45.134410, 'occurrence', 'Lead', array['Lead'], null, array['Hornfels'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY-SOMALIA: UNITED NATIONS REPORT, 133 P.HUNT, J.A., 1960, GEOLOGY OF THE BERBERA-SHEIKH AREA, BERBERA AND BURAU DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT N', '{"mrds_id":"D006925","dev_stat":"Occurrence","ore":"Chalcopyrite, Galena","structure":"N 20 To 30 E Fault","tectonic":"Margin Gulf Of Aden Spreading Center","ore_ctrl":"Fault Zone","prod_size":"N","commod2":"Copper","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011794"}'::jsonb),
  ('10011795', 'Lafarug Prospect', 10.033990, 44.801090, 'occurrence', null, '{}'::text[], null, array['Schist'], 'HUNT, J.A., 1951, A GENERAL SURVEY OF THE SOMALILAND PROTECTORATE 1944-1950: CROWN AGENTS, LONDON, 203 P.FARQUHARSON, M.A., 1924, FIRST REPORT ON THE GEOLOGY AND MINERAL RESOURCES OF BRITISH SOMALILAND: WATERLOW AND SONS LTD., LONDON, 53 P.', '{"mrds_id":"D006935","dev_stat":"Occurrence","ore":"Garnet, Muscovite","prod_size":"N","commod3":"Garnet, Mica","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011795"}'::jsonb),
  ('10011796', 'Marso Prospect', 10.000670, 45.001090, 'occurrence', null, '{}'::text[], null, array['Schist'], 'HUNT, J.A., 1951, A GENERAL SURVEY OF THE SOMALILAND PROTECTORATE 1944-1950: CROWN AGENTS, LONDON, 203 P', '{"mrds_id":"D006936","dev_stat":"Occurrence","ore":"Garnet, Muscovite","prod_size":"N","commod3":"Mica, Garnet","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011796"}'::jsonb),
  ('10011797', 'Huquf Prospect', 9.934000, 45.867740, 'occurrence', null, '{}'::text[], null, array['Schist'], 'HUNT, J.A., 1951, A GENERAL SURVEY OF THE SOMALILAND PROTECTORATE 1944-1950: CROWN AGENTS, LONDON, 203 P', '{"mrds_id":"D006938","dev_stat":"Occurrence","ore":"Garnet","prod_size":"N","commod3":"Garnet","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011797"}'::jsonb),
  ('10011798', 'Salawel Prospect', 10.033990, 45.134410, 'occurrence', null, '{}'::text[], null, array['Schist'], 'HUNT, J.A., 1951, A GENERAL SURVEY OF THE SOMALILAND PROTECTORATE 1944-1950: CROWN AGENTS, LONDON, 203 P', '{"mrds_id":"D006939","dev_stat":"Occurrence","prod_size":"N","commod3":"Manganese","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011798"}'::jsonb),
  ('10011799', 'Bihen Gaha Hot Springs', 10.417290, 45.651070, 'occurrence', null, '{}'::text[], null, '{}'::text[], 'FARQUHARSON, M.A., 1924, FIRST REPORT ON THE GEOLOGY AND MINERAL RESOURCES OF BRITISH SOMALILAND: WATERLOW AND SONS LTD., LF2DON, 53 P.SOMALILAND OIL EXPLORATION COMPANY LTD., 1954, A GEOLOGICAL RECONNAISSANCE OF THE SEDIMENTARY DEPOSITS OF THE PROTECTOR', '{"mrds_id":"D006942","dev_stat":"Occurrence","prod_size":"N","commod3":"Bromine","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011799"}'::jsonb),
  ('10011800', 'Dagahh Kuled Prospect', 11.033890, 48.834350, 'occurrence', null, '{}'::text[], null, array['Schist'], 'HUNT, J. A., 1951, A GENERAL SURVEY OF THE SOMALILAND PROTECTORATE 1944-1950: CROWN AGENTS, LONDON, 203 P', '{"mrds_id":"D006944","dev_stat":"Occurrence","ore":"Rutile","prod_size":"N","commod3":"Titanium, Metal","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011800"}'::jsonb),
  ('10011802', 'Biyo Gora Hot Spring', 10.383960, 45.201080, 'occurrence', null, '{}'::text[], 'Hot Spring', '{}'::text[], 'SOMALILAND OIL EXPLORATION COMPANY LTD., 1954, A GEOLOGICAL RECONNAISSANCE OF THE SEDIMENTARY DEPOSITS OF THE PROTECTORATE OF BRITISH SOMALILAND: CROWN AGENTS, LONDON, 42 P', '{"mrds_id":"D006947","dev_stat":"Occurrence","prod_size":"N","commod3":"Bromine","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011802"}'::jsonb),
  ('10011803', 'Dubar Hot Spring', 10.333960, 45.067750, 'occurrence', null, '{}'::text[], 'Hot Spring', '{}'::text[], 'SOMALILAND OIL EXPLORATION COMPANY LTD., 1954, A GEOLOGICAL RECONNAISSANCE OF THE SEDIMENTARY DEPOSITS OF THE PROTECTORATE OF BRITISH SOMALILAND: CROWN AGENTS, LONDON, 42 P', '{"mrds_id":"D006948","dev_stat":"Occurrence","prod_size":"N","commod3":"Bromine","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011803"}'::jsonb),
  ('10011804', 'Hur Hot Spring', 10.683930, 45.934400, 'occurrence', null, '{}'::text[], 'Hot Spring', '{}'::text[], 'SOMALILAND OIL EXPLORATION COMPANY LTD., 1954, A GEOLOGICAL RECONNAISSANCE OF THE SEDIMENTARY DEPOSITS OF THE PROTECTORATE OF BRITISH SOMALILAND: CROWN AGENTS, LONDON, 42 P', '{"mrds_id":"D006949","dev_stat":"Occurrence","prod_size":"N","commod3":"Bromine","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011804"}'::jsonb),
  ('10011805', 'Qoton Dabo Occurrence', 9.200740, 44.667760, 'occurrence', null, '{}'::text[], null, array['Sandstone'], 'MACFADYEN, W. A., 1952, WATER SUPPLY AND GEOLOGY OF PARTS OF BRITISH SOMALILAND: SOMALILAND BRITISH PROTECTORATE GEOLOGICALSURVEY REPORT, 184 P', '{"mrds_id":"D006950","dev_stat":"Occurrence","ore":"Hematite","hrock_unit":"Nubian Sandstone","prod_size":"N","commod3":"Iron","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011805"}'::jsonb),
  ('10011806', 'Arorigaben Occurrence', 9.217410, 45.051080, 'occurrence', null, '{}'::text[], null, '{}'::text[], 'MACFADYEN, W. A., 1952, WATER SUPPLY AND GEOLOGY OF PARTS OF BRITISH SOMALILAND: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT, 184 P', '{"mrds_id":"D006951","dev_stat":"Occurrence","ore":"Hematite","prod_size":"N","commod3":"Iron","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011806"}'::jsonb),
  ('10011807', 'Doboweina Occurence', 9.300730, 44.867750, 'occurrence', null, '{}'::text[], null, array['Sandstone'], 'MACFADYEN, W.A., 1952, WATER SUPPLY AND GEOLOGY OF PARTS OF BRITISH-SOMALILAND. SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT, 184P', '{"mrds_id":"D006952","dev_stat":"Occurrence","ore":"Hematite","hrock_unit":"Nubian Sandstone","prod_size":"N","commod3":"Iron","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011807"}'::jsonb),
  ('10011808', 'Elk Occurrence', 8.967430, 45.334400, 'occurrence', null, '{}'::text[], null, array['Sandstone'], 'MACFADYEN, W.A., 1952, WATER SUPPLY AND GEOLOGY OF PARTS OF BRITISH SOMALILAND. SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT, 184P', '{"mrds_id":"D006953","dev_stat":"Occurrence","ore":"Hematite","hrock_unit":"Nubian Sandstone","prod_size":"N","commod3":"Iron","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011808"}'::jsonb),
  ('10011809', 'Hargeisa-Awareh Road Occurrence', 9.350730, 44.067770, 'occurrence', null, '{}'::text[], null, array['Sandstone'], 'MACFADYEN, W.A., 1952, WATER SUPPLY AND GEOLOGY OF PARTS OF BRITISH SOMALILAND: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT, 184 P', '{"mrds_id":"D006954","dev_stat":"Occurrence","ore":"Hematite","hrock_unit":"Nubian Sandstone","prod_size":"N","commod3":"Iron","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011809"}'::jsonb),
  ('10011810', 'Waran-Weis Occurrence', 10.150650, 43.851100, 'occurrence', null, '{}'::text[], null, array['Schist'], 'DANIELS, J.L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D006955","dev_stat":"Occurrence","ore":"Beryl, Columbite","prod_size":"N","commod3":"Beryllium, Niobium (Columbium), Quartz","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011810"}'::jsonb),
  ('10011811', 'Ubali Occurrence', 9.934010, 43.751100, 'occurrence', null, '{}'::text[], null, array['Schist'], 'DANIELS, J.L., 1960, MINERALS AND ROCKS OF HARHEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D006956","dev_stat":"Occurrence","ore":"Beryl","prod_size":"N","commod3":"Beryllium","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011811"}'::jsonb),
  ('10011812', 'Marodile Occurrence', 9.917350, 43.901100, 'occurrence', null, '{}'::text[], null, array['Schist'], 'DANIELS, J.L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D006957","dev_stat":"Occurrence","ore":"Beryl, Graphite","prod_size":"N","commod3":"Beryllium, Graphite","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011812"}'::jsonb),
  ('10011813', 'Rakdasafaka Occurrence', 10.000680, 43.834430, 'occurrence', null, '{}'::text[], null, array['Schist'], 'DANIELS, J.L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D006958","dev_stat":"Occurrence","ore":"Graphite","prod_size":"N","commod3":"Graphite","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011813"}'::jsonb),
  ('10011814', 'Mirid Occurrence', 10.150660, 43.751110, 'occurrence', null, '{}'::text[], null, array['Schist'], 'DANIELS, J.L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D006959","dev_stat":"Occurrence","ore":"Kyanite","prod_size":"N","commod3":"Kyanite","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011814"}'::jsonb),
  ('10011815', 'Damal Occurrence', 10.533950, 43.301110, 'occurrence', null, '{}'::text[], null, array['Schist'], 'DANIELS, J.L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D006960","dev_stat":"Occurrence","ore":"Kyanite","prod_size":"N","commod3":"Kyanite","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011815"}'::jsonb),
  ('10011816', 'Ubali Occurrence', 9.934000, 43.901100, 'occurrence', 'Manganese', array['Manganese'], null, array['Schist'], 'DANIELS, J.L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D006961","dev_stat":"Occurrence","ore":"Rhodonite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011816"}'::jsonb),
  ('10011817', 'Wai-Wai Occurrence', 10.217320, 43.667780, 'occurrence', null, '{}'::text[], null, array['Schist'], 'DANIELS, J.L., 1960, MINERALS AND ROCKS OF HARHEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D006962","dev_stat":"Occurrence","ore":"Quartz","prod_size":"N","commod3":"Quartz","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011817"}'::jsonb),
  ('10011818', 'Darkainle Occurrence', 10.400630, 43.284440, 'occurrence', null, '{}'::text[], null, array['Schist'], 'DANIELS, J.L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25P', '{"mrds_id":"D006963","dev_stat":"Occurrence","ore":"Pyrochlore","prod_size":"N","commod3":"Niobium (Columbium), Uranium","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011818"}'::jsonb),
  ('10011819', 'Waran-Weis Occurrence', 10.150650, 43.867770, 'occurrence', null, '{}'::text[], null, array['Schist'], 'DANIELS, J.L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D006964","dev_stat":"Occurrence","ore":"Rutile","prod_size":"N","commod3":"Titanium, Metal","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011819"}'::jsonb),
  ('10011820', 'Biyo Dader Occurrence', 9.917350, 43.534440, 'occurrence', null, '{}'::text[], null, array['Schist'], 'DANIELS, J.L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D006965","dev_stat":"Occurrence","ore":"Rutile","prod_size":"N","commod3":"Titanium, Metal","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011820"}'::jsonb),
  ('10011821', 'Rakdasafaka Occurrence', 9.950670, 43.851100, 'occurrence', 'Gemstone', array['Gemstone'], null, array['Mafic Metamorphic Rock'], 'DANIELS, J.L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D006966","dev_stat":"Occurrence","ore":"Spinel","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011821"}'::jsonb),
  ('10011822', 'Qoton Occurrence', 10.467300, 43.134450, 'occurrence', null, '{}'::text[], null, array['Ultramafic Intrusive Rock'], 'DANIELS, J.L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D006967","dev_stat":"Occurrence","ore":"Talc","prod_size":"N","commod3":"Talc-Soapstone","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011822"}'::jsonb),
  ('10011823', 'Biji Occurrence', 10.167320, 43.984430, 'occurrence', null, '{}'::text[], null, array['Marble'], 'DANIELS, J.L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D006968","dev_stat":"Occurrence","ore":"Talc, Vermiculite","gangue":"Corundum, Spinel","prod_size":"N","commod3":"Talc-Soapstone, Vermiculite","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011823"}'::jsonb),
  ('10011824', 'B1yo Dader Occurrence', 9.917350, 43.534440, 'occurrence', 'Silica', array['Silica'], null, array['Sandstone'], 'DANIELS, J.L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SUMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25P', '{"mrds_id":"D006969","dev_stat":"Occurrence","ore":"Sand","hrock_unit":"Adigrat Sandstone","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011824"}'::jsonb),
  ('10011825', 'Mur Bakayale Mine', 10.017330, 44.867760, 'past_producer', 'Beryllium', array['Beryllium','Niobium (Columbium)'], null, array['Schist'], 'MASON, J.E., 1962, GEOLOGY OF THE AREA NORTH OF HARGEISA AND LAFERUG; HARGEISA AND BERBERA DISTRICTS: SOMALIA GEOLOGICAL SURVEY REPORT NO. 7, 34 P', '{"mrds_id":"D006970","dev_stat":"Past Producer","ore":"Allanite, Beryl, Columbite, Ilmenite, Muscovite","prod_size":"S","commod2":"Mica","commod3":"Titanium, Metal","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011825"}'::jsonb),
  ('10011826', 'Las Gal Tug Occurrence', 10.167320, 44.734420, 'occurrence', null, '{}'::text[], null, array['Gabbro'], 'MASON, J.E., 1962, GEOLOGY OF THE AREA NORTH OF HARGEISA AND LAFERUG, HARGEISA AND BERBERA DISTRICTS: SOMALIA GEOLOGICAL SURVEY REPORT NO. 7, 34 P', '{"mrds_id":"D006971","dev_stat":"Occurrence","ore":"Beryl","gangue":"Tourmaline","prod_size":"N","commod3":"Beryllium","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011826"}'::jsonb),
  ('10011827', 'Teaq Tug Occurrence', 10.067330, 44.867760, 'occurrence', null, '{}'::text[], null, array['Gneiss'], 'MASON, J.E., 1962, GEOLOGY OF THE AREA NORTH OF HARGEISA AND LAFERUG, HARGEISA AND BERBERA DISTRICTS: SOMALIA GEOLOGICAL SURVEY REPORT NO. 7, 34 P', '{"mrds_id":"D006972","dev_stat":"Occurrence","ore":"Beryl","prod_size":"N","commod3":"Beryllium","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011827"}'::jsonb),
  ('10011828', 'Qodli Occurrence', 10.133980, 44.684420, 'occurrence', null, '{}'::text[], null, array['Schist'], 'MASON, J.E., 1962, GEOLOGY OF THE AREA NORTH OF HARGEISA AND LAFERUG, HARGEISA AND BERBERA DISTRICTS: SOMALIA GOLOGICAL SURVEY REPORT NO. 7, 34 P', '{"mrds_id":"D006973","dev_stat":"Occurrence","prod_size":"N","commod3":"Asbestos","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011828"}'::jsonb),
  ('10011829', 'Sarar Awr Occurrence', 10.017330, 44.517760, 'occurrence', 'Silica', array['Silica'], null, array['Sandstone'], 'MASON, J.E., 1962, GEOLOGY OF THE AREA NORTH OF HARGEISA AND LAFERUG, HARGEISA AND BERBERA DISTRICTS: SOMALIA GEOLOGICAL SURVEY REPORT NO. 7, 34 P', '{"mrds_id":"D006974","dev_stat":"Occurrence","ore":"Sand","hrock_unit":"Nubian Sandstone","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011829"}'::jsonb),
  ('10011830', 'Afka Dehemid Prospect', 10.017330, 45.701070, 'occurrence', 'Talc-Soapstone', array['Talc-Soapstone'], 'Metamorphic', '{}'::text[], 'GELLATLY, D.C., 1960, GEOLOGY OF THE LAS DUREH AREA, BURAO DISTRICT: SOMALIA GEOLOGICAL SURVEY REPORT NO. 6, 40 P', '{"mrds_id":"D006976","dev_stat":"Occurrence","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011830"}'::jsonb),
  ('10011831', 'Hulul Prospect', 10.200650, 45.084410, 'occurrence', 'Barium-Barite', array['Barium-Barite','Lead','Fluorine-Fluorite'], null, array['Granite'], 'HUNT, J.A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PORTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27', '{"mrds_id":"D006977","dev_stat":"Occurrence","ore":"Barite, Chalcopyrite, Fluorite, Galena","prod_size":"N","commod2":"Copper","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011831"}'::jsonb),
  ('10011832', 'Ido Faito Occurrence', 10.167320, 45.001090, 'occurrence', 'Beryllium', array['Beryllium'], null, '{}'::text[], 'HUNT, J.A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D006978","dev_stat":"Occurrence","ore":"Beryl","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011832"}'::jsonb),
  ('10011833', 'Bur Safarnolei Occurrence', 2.584680, 43.184430, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006980","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011833"}'::jsonb),
  ('10011834', 'Bur Mun Occurrence', 2.268050, 43.034430, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006981","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011834"}'::jsonb),
  ('10011835', 'Bur El Mahala Occurrence', 2.601350, 43.101100, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006983","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011835"}'::jsonb),
  ('10011836', 'Bur Bascir Occurrence', 2.551360, 43.067770, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006984","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011836"}'::jsonb),
  ('10011837', 'Bur Roborugei Occurrence', 2.534690, 43.117770, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006986","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011837"}'::jsonb),
  ('10011838', 'Bur Gerei Occurrence', 2.334710, 43.117770, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006987","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011838"}'::jsonb),
  ('10011839', 'Bur Irmogugi Occurrence', 2.234720, 43.301100, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006989","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011839"}'::jsonb),
  ('10011840', 'Bur Medov Occurrence', 2.268050, 43.417760, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006990","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011840"}'::jsonb),
  ('10011841', 'Bur Gheluai Occurrence', 2.351380, 43.567760, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R. J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006992","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011841"}'::jsonb),
  ('10011842', 'Bur Ziave Occurrence', 2.268050, 43.534420, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R. J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A.45-125) REPORT, 63 P', '{"mrds_id":"D006993","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011842"}'::jsonb),
  ('10011843', 'Bur Gheiden Occurrence', 2.651350, 43.751090, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R. J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): US.S TECHNICAL ASSISTANCE MISSION(T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006995","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011843"}'::jsonb),
  ('10011844', 'Bur Eile Occurrence', 3.034640, 44.267750, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R. J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006996","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011844"}'::jsonb),
  ('10011845', 'Bisseqh Adde Occurrence', 2.468030, 43.751090, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'UNITED NATIONAS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133 P', '{"mrds_id":"D006999","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011845"}'::jsonb),
  ('10011846', 'Yaq Brava Prospect', 2.118070, 43.201100, 'prospect', 'Thorium', array['Thorium'], 'Vein', array['Schist'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133 P', '{"mrds_id":"D007000","dev_stat":"Prospect","prod_size":"N","commod2":"Uranium","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011846"}'::jsonb),
  ('10011847', 'Bur Mun Occurrence', 2.234720, 43.001110, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R. J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): US.S TECHNICAL ASSISTANCEMISSION (TA.A 45-125) REPORT, 83 P', '{"mrds_id":"D007001","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011847"}'::jsonb),
  ('10011848', 'Unnamed Radioactivity Anomaly', 2.351380, 43.051100, 'prospect', null, '{}'::text[], 'Contact Metasomatic', array['Quartzite'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133 P', '{"mrds_id":"D007003","dev_stat":"Prospect","prod_size":"N","commod3":"Thorium, Uranium","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011848"}'::jsonb),
  ('10011849', 'Unnamed Radioactivity Anomaly', 2.518030, 42.984430, 'prospect', null, '{}'::text[], 'Contact Metasomatic', array['Quartzite'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133 P', '{"mrds_id":"D007004","dev_stat":"Prospect","prod_size":"N","commod3":"Thorium, Uranium","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011849"}'::jsonb),
  ('10011850', 'Unnamed Radioactive Anomaly', 2.668020, 43.367770, 'prospect', null, '{}'::text[], 'Contact Metasomatic', array['Quartzite','Schist'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133P', '{"mrds_id":"D007006","dev_stat":"Prospect","prod_size":"N","commod3":"Thorium, Uranium","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011850"}'::jsonb),
  ('10011851', 'Gal Hamud Occurrence', 10.167320, 45.051080, 'occurrence', null, '{}'::text[], null, array['Sandstone'], 'HUNT, J. A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007007","dev_stat":"Occurrence","ore":"Chalcopyrite","hrock_unit":"Adigrat Sandstone","prod_size":"N","commod3":"Copper","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011851"}'::jsonb),
  ('10011852', 'Elan Gubado Prospect', 10.000670, 45.201080, 'occurrence', null, '{}'::text[], null, array['Granite'], 'HUNT, J. S., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007008","dev_stat":"Occurrence","ore":"Chalcopyrite, Malachite","prod_size":"N","commod3":"Copper","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011852"}'::jsonb),
  ('10011853', 'Ardahh Prospect', 10.167320, 45.084410, 'occurrence', 'Lead', array['Lead','Barium-Barite'], null, array['Sandstone'], 'HUNT, J. A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007009","dev_stat":"Occurrence","ore":"Barite, Fluorite, Galena","hrock_unit":"Adigrat Sandstone","prod_size":"N","commod2":"Fluorine-Fluorite","commod3":"Iron","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011853"}'::jsonb),
  ('10011854', 'Hul Qabobe Occurrence', 10.000670, 45.051080, 'occurrence', 'Iron', array['Iron'], null, array['Amphibole Schist'], 'HUNT, J. A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007011","dev_stat":"Occurrence","ore":"Magnetite","gangue":"Apatite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011854"}'::jsonb),
  ('10011855', 'Didin Occurrence', 10.183980, 45.017750, 'occurrence', 'Iron', array['Iron'], null, array['Gabbro'], 'HUNT, J. A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007012","dev_stat":"Occurrence","ore":"Magnetite","gangue":"Apatite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011855"}'::jsonb),
  ('10011856', 'Daimoleh Wein Occurrence', 10.100660, 45.051080, 'occurrence', 'Iron', array['Iron','Manganese'], null, array['Migmatite'], 'HUNT, J. A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007014","dev_stat":"Occurrence","ore":"Rhodonite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011856"}'::jsonb),
  ('10011857', 'Marso Occurrence', 9.984000, 45.067750, 'occurrence', 'Manganese', array['Manganese'], null, array['Schist'], 'HUNT, J. A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007016","dev_stat":"Occurrence","ore":"Rhodonite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011857"}'::jsonb),
  ('10011858', 'Lalis Occurrence', 10.083990, 45.167750, 'occurrence', 'Manganese', array['Manganese'], null, array['Schist'], 'HUNT, J. A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007018","dev_stat":"Occurrence","ore":"Rhodonite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011858"}'::jsonb),
  ('10011859', 'Manja Asseh Occurrence', 10.133980, 45.117750, 'occurrence', 'Manganese', array['Manganese'], null, array['Schist'], 'HUNT, J. A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007021","dev_stat":"Occurrence","ore":"Rhodonite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011859"}'::jsonb),
  ('10011860', 'Luqunlo Ad Occurrence', 9.984000, 45.167750, 'occurrence', 'Manganese', array['Manganese'], null, array['Granite'], 'HUNT, J. A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007022","dev_stat":"Occurrence","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011860"}'::jsonb),
  ('10011861', 'Sanka Hodeiga Occurrence', 10.033990, 45.101080, 'occurrence', 'Quartz', array['Quartz'], null, '{}'::text[], 'HUNT, J. A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007024","dev_stat":"Occurrence","ore":"Quartz","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011861"}'::jsonb),
  ('10011862', 'Dagahh Dai Occurr5nce', 9.967340, 45.051080, 'occurrence', 'Talc-Soapstone', array['Talc-Soapstone'], 'Metamorphic', array['Schist'], 'HUNT, J. A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA 1N4 BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007026","dev_stat":"Occurrence","ore":"Talc","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011862"}'::jsonb),
  ('10011863', 'Shabel Weina Occurrence', 10.017330, 45.034410, 'occurrence', 'Talc-Soapstone', array['Talc-Soapstone'], 'Metamorphic', array['Schist'], 'HUNT, J. A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007027","dev_stat":"Occurrence","ore":"Talc","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011863"}'::jsonb),
  ('10011864', 'Veliya Tug Occurrence', 11.067220, 48.751020, 'occurrence', 'Lead', array['Lead','Barium-Barite'], null, array['Limestone'], 'GREENWOOD, J. E. G. W., 1960, GEOLOGY OF THE LAS KHOREH - ELAYU AREA, ERIGAVO DISTRICT: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 3, 36 P', '{"mrds_id":"D007029","dev_stat":"Occurrence","ore":"Barite, Galena","tectonic":"Margin, Gulf Of Aden Spreading Center","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011864"}'::jsonb),
  ('10011865', 'Mokhor Holeh Occurrence', 11.067220, 48.884350, 'occurrence', 'Lead', array['Lead','Barium-Barite'], null, array['Mudstone'], 'GREENWOOD, J. E. G. W., 1960, GEOLOGY OF THE LAS KHOREH - ELAYU AREA, ERIGAVO DISTRICT: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 3, 36 P', '{"mrds_id":"D007031","dev_stat":"Occurrence","ore":"Barite, Galena","gangue":"Quartz","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011865"}'::jsonb),
  ('10011866', 'Karin Kul Occurrence', 11.133880, 48.484360, 'occurrence', 'Lead', array['Lead','Barium-Barite'], null, '{}'::text[], 'GREENWOOD, J. E. G. W., 1960, GEOLOGY OF THE LAS KHOREH - ELAYU AREA, ERIGAVO DISTRICT: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 3, 36 P', '{"mrds_id":"D007032","dev_stat":"Occurrence","ore":"Barite, Galena","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011866"}'::jsonb),
  ('10011867', 'Karajiv Occurrence', 11.100550, 48.667690, 'occurrence', 'Lead', array['Lead','Barium-Barite'], null, '{}'::text[], 'GREENWOOD, J. E. G. W., 1960, GEOLOGY OF THE LAS KHOREH - ELAYU AREA, ERIGAVO DISTRICT: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 3, 36 P', '{"mrds_id":"D007034","dev_stat":"Occurrence","ore":"Barite, Galena","gangue":"Quartz","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011867"}'::jsonb),
  ('10011868', 'Unkah Prospect', 10.083980, 48.451020, 'occurrence', 'Lead', array['Lead','Silver','Barium-Barite'], null, array['Slate'], 'FARQUHARSON, M. A., 1924, FIRST REPORT ON THE GEOLOGY AND MINERAL RESOURCES OF BRITISH SOMALILAND: WATERLOW AND SONS LTD., LONDON, 53 P', '{"mrds_id":"D007036","dev_stat":"Occurrence","gangue":"Chalcedony","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011868"}'::jsonb),
  ('10011869', 'Darinwadu Tug Occurrence', 10.533950, 43.317780, 'occurrence', 'Garnet', array['Garnet'], null, array['Schist'], 'FARQUHARSON, M. A., 1924, FIRST REPORT ON THE GEOLOGY AND MINERAL RESOURCES OF BRITISH SOMALILAND: WATERLOW AND SONS LTD., LONDON, 53 P', '{"mrds_id":"D007039","dev_stat":"Occurrence","ore":"Garnet","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011869"}'::jsonb),
  ('10011870', 'Ardeh Prospect', 10.167320, 45.134410, 'occurrence', 'Barium-Barite', array['Barium-Barite'], null, array['Gneiss'], 'FARQUHARSON, M. A., 1924, FIRST REPORT ON THE GEOLOGY AND MINERAL RESOURCES OF BRITISH SOMALILAND: WATERLOW AND SONS LTD., LONDON, 53 P', '{"mrds_id":"D007040","dev_stat":"Occurrence","ore":"Barite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011870"}'::jsonb),
  ('10011871', 'Dobo Well Occurrence', 10.250650, 43.217780, 'occurrence', 'Molybdenum', array['Molybdenum'], null, array['Gneiss'], 'FARQUHARSON, M. A., 1924, FIRST REPORT ON THE GEOLOGY AND MINERAL RESOURCES OF BRITISH SOMALILAND: WATERLOW AND SONS LTD., LONDON, 53 P', '{"mrds_id":"D007041","dev_stat":"Occurrence","ore":"Molybdenite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011871"}'::jsonb),
  ('10011872', 'Himbir Wein Occurrence', 10.250640, 45.517750, 'occurrence', 'Strontium', array['Strontium'], null, array['Shale'], 'FARQUHARSON, M. A., 1924, FIRST REPORT ON THE GEOLOGY AND MINERAL REOURCES OF BRITISH SOMALILAND: WATERLOW AND SONS LTD., LONDON, 53 P', '{"mrds_id":"D007043","dev_stat":"Occurrence","hrock_unit":"Anhydrite Series","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011872"}'::jsonb),
  ('10011873', 'Bayal Well Occurrence', 10.217310, 45.134410, 'occurrence', 'Fullers Earth', array['Fullers Earth'], null, '{}'::text[], 'FARQUHARSON, M. A., 1924, FIRST REPORT ON THE GEOLOGY AND MINERAL RESOURCES OF BRITISH SOMALILAND: WATERLOW AND SONS LTD., LONDON, 53 P', '{"mrds_id":"D007044","dev_stat":"Occurrence","ore":"Montmorillonite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011873"}'::jsonb),
  ('10011874', 'Durdur Ad Tug', 10.233980, 43.601110, 'occurrence', 'Stone', array['Stone','Crushed','Broken'], 'Sedimentary', array['Shale'], 'FARQUHARSON, M. A., 1924, FIRST REPORT ON THE GEOLOGY AND MINERAL RESOURCES OF BRITISH SOMALILAND: WATERLOW AND SONS LTD., LONDON, 53 P', '{"mrds_id":"D007046","dev_stat":"Occurrence","ore":"Oil Shale","hrock_unit":"Bihen Limestone","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011874"}'::jsonb),
  ('10011875', 'Dalan Prospect', 11.083880, 48.817690, 'past_producer', 'Tin', array['Tin'], null, array['Gabbro'], 'GREENWOOD, J. E. G. W., 1960, GEOLOGY OF THE LAS KHOREH - ELAYU AREA, ERIGAVO DISTRICT: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 3, 36 P.PALLISTER, J. W., 1959, MINERAL RESOURCES OF THE SOMALILAND PROTECTORATE: SOMALILAND BRITISH PR', '{"mrds_id":"D007047","dev_stat":"Past Producer","ore":"Cassiterite","prod_size":"S","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011875"}'::jsonb),
  ('10011876', 'Dobo Occurrence', 10.300640, 43.301110, 'occurrence', 'Niobium (Columbium)', array['Niobium (Columbium)'], null, array['Schist'], 'DANIELS, J. L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D007050","dev_stat":"Occurrence","ore":"Columbite, Molybdenite","prod_size":"N","commod3":"Molybdenum","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011876"}'::jsonb),
  ('10011877', 'Hamar Occurrence', 9.967340, 43.851100, 'occurrence', 'Beryllium', array['Beryllium'], null, array['Schist'], 'DANIELS, J. L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D007051","dev_stat":"Occurrence","ore":"Beryl","gangue":"Graphite, Magnetite, Spinel","prod_size":"N","commod2":"Iron, Graphite","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011877"}'::jsonb),
  ('10011878', 'Mirid Occurrence', 10.183980, 43.617780, 'occurrence', 'Copper', array['Copper','Barium-Barite'], null, array['Schist'], 'DANIELS, J. L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D007053","dev_stat":"Occurrence","ore":"Barite, Beryl, Chalcopyrite, Kyanite","prod_size":"N","commod2":"Kyanite, Beryllium","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011878"}'::jsonb),
  ('10011879', 'Il Haggar Occurrence', 10.217320, 43.717780, 'occurrence', 'Mica', array['Mica','Molybdenum','Beryllium','Niobium (Columbium)'], null, array['Schist'], 'DANIELS, J. L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D007055","dev_stat":"Occurrence","ore":"Beryl, Columbite, Molybdenite, Muscovite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011879"}'::jsonb),
  ('10011880', 'Bawn Occurrence', 10.200650, 43.101120, 'occurrence', 'Beryllium', array['Beryllium'], null, array['Schist'], 'DANIELS, J. L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERALS RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D007056","dev_stat":"Occurrence","ore":"Beryl","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011880"}'::jsonb),
  ('10011881', 'Unnamed Radioactivity Anomaly', 3.051310, 44.317750, 'occurrence', 'Thorium', array['Thorium','Uranium'], null, '{}'::text[], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133 P', '{"mrds_id":"D007058","dev_stat":"Occurrence","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011881"}'::jsonb),
  ('10011882', 'Unnamed Magnetic Anomaly', 2.734670, 43.201100, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133 P', '{"mrds_id":"D007060","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011882"}'::jsonb),
  ('10011883', 'Unnamed Magnetic Anomaly', 2.834660, 43.234430, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133 P', '{"mrds_id":"D007061","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011883"}'::jsonb),
  ('10011884', 'Bur Acaba Magnetic Anomaly', 2.751340, 44.167750, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133 P', '{"mrds_id":"D007063","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011884"}'::jsonb),
  ('10011885', 'Unnamed Magnetic Anomaly', 2.868000, 44.401080, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133 P', '{"mrds_id":"D007065","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011885"}'::jsonb),
  ('10011886', 'Manas Occurrence', 2.884660, 43.451090, 'occurrence', 'Aluminum', array['Aluminum'], null, array['Limestone'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133 P', '{"mrds_id":"D007067","dev_stat":"Occurrence","ore":"Bauxite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011886"}'::jsonb),
  ('10011887', 'Bur Acaba Occurrence', 2.868000, 44.084410, 'occurrence', null, '{}'::text[], null, '{}'::text[], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133 P', '{"mrds_id":"D007068","dev_stat":"Occurrence","prod_size":"N","commod3":"Silver, Copper, Tin","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011887"}'::jsonb),
  ('10011888', 'Unnamed Stream Sample Anomaly', 3.034640, 43.751090, 'occurrence', null, '{}'::text[], null, '{}'::text[], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133 P', '{"mrds_id":"D007069","dev_stat":"Occurrence","prod_size":"N","commod3":"Copper, Tin, Silver","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011888"}'::jsonb),
  ('10011889', 'Baidoa Occurrence', 3.201300, 43.717760, 'occurrence', 'Aluminum', array['Aluminum'], null, '{}'::text[], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133P', '{"mrds_id":"D007071","dev_stat":"Occurrence","ore":"Bauxite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011889"}'::jsonb),
  ('10011890', 'Unnamed Bauxite Occurrence', 3.117980, 43.567760, 'occurrence', 'Aluminum', array['Aluminum'], null, '{}'::text[], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133P', '{"mrds_id":"D007073","dev_stat":"Occurrence","ore":"Bauxite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011890"}'::jsonb),
  ('10011891', 'Unnamed Bauxite Occurrence', 3.217970, 43.417770, 'occurrence', 'Aluminum', array['Aluminum'], null, '{}'::text[], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133P', '{"mrds_id":"D007074","dev_stat":"Occurrence","ore":"Bauxite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011891"}'::jsonb),
  ('10011892', 'Modu Mode Occurrence', 3.051310, 43.867760, 'occurrence', 'Phosphorus-Phosphates', array['Phosphorus-Phosphates'], null, array['Marble'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133P', '{"mrds_id":"D007075","dev_stat":"Occurrence","hrock_unit":"Icia Baidoa Formation","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011892"}'::jsonb),
  ('10011893', 'Asilihe Prospect', 11.100550, 48.834350, 'occurrence', 'Tin', array['Tin'], null, array['Sandstone'], 'GREENWOOD, J. E. G. W., 1960, GEOLOGY OF THE LAS KHOREH - ELAYU AREA, ERIGAVO DISTRICT: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 3, 36 P.PALLISTER, J.W., 1959, MINERAL RESOURCES OF SOMALILAND PROTECTORATE: SOMALILAND BRITISH PROTECTO', '{"mrds_id":"D007078","dev_stat":"Occurrence","ore":"Cassiterite","hrock_unit":"Inda Ad Series","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011893"}'::jsonb),
  ('10011894', 'Daarbuduq Occurrence', 9.850680, 44.534420, 'occurrence', 'Asbestos', array['Asbestos'], null, '{}'::text[], 'HUNT, J.A., 1958, GEOLOGY OF THE ADADLEH AREA, HARGEISA AND BERBERA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 2, 16 P', '{"mrds_id":"D007079","dev_stat":"Occurrence","ore":"Anthophyllite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011894"}'::jsonb),
  ('10011895', 'Barkasan Occurrence', 9.967340, 44.751090, 'occurrence', 'Molybdenum', array['Molybdenum'], null, '{}'::text[], 'HUNT, J.A., 1958, GEOLOGY OF THE ADADLEH AREA, HARGEISA AND BERBERA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 2, 16 P', '{"mrds_id":"D007081","dev_stat":"Occurrence","ore":"Molybdenite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011895"}'::jsonb),
  ('10011896', 'Abderesach Occurrence', 11.350520, 49.951000, 'occurrence', 'Barium-Barite', array['Barium-Barite','Lead'], null, array['Limestone'], 'USONI, LUIGI, 1952, RICORSE MINERARIE DELL ''AFRICA ORIENTALE; ERITREA, ETIOPIA, SOMALIA: JANDI SAPI, ROMA, 553 P', '{"mrds_id":"D007082","dev_stat":"Occurrence","ore":"Barite, Galena","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10011896"}'::jsonb),
  ('10038694', 'Dibrawein', 9.934010, 43.184440, 'occurrence', null, '{}'::text[], null, array['Gabbro'], '1. COLONIAL OFFICE, 1959, BEARD, E. H., ED., OVERSEAS GEOL. & MIN. RES., V. 7., P. 417', '{"mrds_id":"M046112","dev_stat":"Occurrence","prod_size":"N","commod3":"Chromium, Nickel, Platinum","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10038694"}'::jsonb),
  ('10090840', 'Garba Rared Occurrence', 10.050660, 45.117750, 'occurrence', 'Iron', array['Iron'], null, array['Gabbro'], 'HUNT, J. A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007013","dev_stat":"Occurrence","ore":"Magnetite, Pyrite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090840"}'::jsonb),
  ('10090841', 'Hirmadleh Occurrence', 10.033990, 45.167750, 'occurrence', 'Manganese', array['Manganese'], null, array['Schist'], 'HUNT, J. A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007017","dev_stat":"Occurrence","ore":"Rhodonite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090841"}'::jsonb),
  ('10090842', 'Asaha Gotin Occurrence', 10.017330, 45.134410, 'occurrence', 'Manganese', array['Manganese'], null, array['Schist'], 'HUNT, J. A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007019","dev_stat":"Occurrence","ore":"Rhodonite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090842"}'::jsonb),
  ('10090843', 'Wadaba Occurrence', 10.033990, 45.034410, 'occurrence', 'Quartz', array['Quartz'], null, '{}'::text[], 'HUNT, J. A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007023","dev_stat":"Occurrence","ore":"Quartz","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090843"}'::jsonb),
  ('10090845', 'Magar Occurrence', 11.017230, 48.617690, 'occurrence', 'Lead', array['Lead','Barium-Barite'], null, array['Siltstone'], 'GREENWOOD, J. E. G. W., 1960, GEOLOGY OF THE LAS KHOREH - ELAYU AREA, ERIGAVO DISTRICT: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 3, 36 P', '{"mrds_id":"D007028","dev_stat":"Occurrence","ore":"Barite, Galena","structure":"N70w","tectonic":"Margin Gulf Of Aden Spreading Center","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090845"}'::jsonb),
  ('10090846', 'Idiq Occurrence', 11.033890, 48.784350, 'occurrence', 'Lead', array['Lead','Barium-Barite'], null, array['Sandstone'], 'GREENWOOD, J. E. G. W., 1960, GEOLOGY OF THE LAS KHOREH - ELAYU AREA, ERIGAVO DISTRICT: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 3, 36 P', '{"mrds_id":"D007030","dev_stat":"Occurrence","ore":"Barite, Galena","gangue":"Quartz","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090846"}'::jsonb),
  ('10090847', 'Gedad Occurrence', 11.083880, 48.501030, 'occurrence', 'Lead', array['Lead','Barium-Barite'], null, '{}'::text[], 'GREENWOOD, J. E. G. W., 1960, GEOLOGY OF THE LAS KHOREH - ELAYU AREA, ERIGAVO DISTRICT: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 3, 36 P', '{"mrds_id":"D007033","dev_stat":"Occurrence","ore":"Barite, Galena","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090847"}'::jsonb),
  ('10090848', 'Durriehauseh Occurrence', 9.950670, 44.751090, 'occurrence', 'Beryllium', array['Beryllium','Mica'], null, '{}'::text[], 'FARQUHARSON, M. A., 1924, FIRST REPORT ON THE GEOLOGY AND MINERAL RESOURCES OF BRITISH SOMALILAND: WATERLOW AND SONS LTD., LONDON, 53 P', '{"mrds_id":"D007038","dev_stat":"Occurrence","ore":"Beryl, Muscovite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090848"}'::jsonb),
  ('10090849', 'Darass Occurrence', 10.000680, 44.967750, 'occurrence', 'Talc-Soapstone', array['Talc-Soapstone'], 'Metamorphic', array['Schist'], 'FARQUHARSON, M. A., 1924, FIRST REPORT ON THE GEOLOGY AND MINERAL RESOURCES OF BRITISH SOMALILAND: WATERLOW AND SONS LTD., LONDON, 53 P', '{"mrds_id":"D007045","dev_stat":"Occurrence","ore":"Talc","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090849"}'::jsonb),
  ('10090850', 'Dobo Occurrence', 10.267320, 43.284440, 'occurrence', 'Niobium (Columbium)', array['Niobium (Columbium)'], null, array['Schist'], 'DANIELS, J. L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D007049","dev_stat":"Occurrence","ore":"Columbite, Molybdenite","prod_size":"N","commod3":"Molybdenum","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090850"}'::jsonb),
  ('10090851', 'Mora Occurrence', 9.917350, 43.784430, 'occurrence', 'Talc-Soapstone', array['Talc-Soapstone','Asbestos'], null, array['Marble'], 'DANIELS, J. L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D007052","dev_stat":"Occurrence","ore":"Asbestos, Talc","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090851"}'::jsonb),
  ('10090852', 'Wai Wai Occurrence', 10.217320, 43.667780, 'occurrence', 'Beryllium', array['Beryllium','Manganese'], null, array['Schist'], 'DANIELS, J. L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D007054","dev_stat":"Occurrence","ore":"Beryl, Rhodonite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090852"}'::jsonb),
  ('10090853', 'Theb Occurrence', 10.150650, 43.851100, 'occurrence', 'Beryllium', array['Beryllium','Bismuth'], null, array['Schist'], 'DANIELS, J. L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D007057","dev_stat":"Occurrence","ore":"Beryl, Bismuthinite, Bismutite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090853"}'::jsonb),
  ('10090854', 'Bur Coreh Magnetic Anomaly', 1.951410, 43.434420, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133 P', '{"mrds_id":"D007059","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090854"}'::jsonb),
  ('10090855', 'Daimir Magnetic Anomaly', 2.868000, 43.334430, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133 P', '{"mrds_id":"D007062","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090855"}'::jsonb),
  ('10090856', 'Bur Acaba Magnetic Anomaly', 2.884660, 44.134410, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133 P', '{"mrds_id":"D007064","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090856"}'::jsonb),
  ('10090857', 'Unnamed Magnetic Anomaly', 3.084640, 44.351080, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133 P', '{"mrds_id":"D007066","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090857"}'::jsonb),
  ('10090858', 'Baidoa Stream Sample Anomaly', 3.201300, 43.717760, 'occurrence', null, '{}'::text[], null, '{}'::text[], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY-SOMALIA: UNITED NATIONS REPORT, 133P', '{"mrds_id":"D007070","dev_stat":"Occurrence","prod_size":"N","commod3":"Silver","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090858"}'::jsonb),
  ('10090859', 'Unnamed Bauxite Occurrence', 3.001330, 43.501090, 'occurrence', 'Aluminum', array['Aluminum'], null, '{}'::text[], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133', '{"mrds_id":"D007072","dev_stat":"Occurrence","ore":"Bauxite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090859"}'::jsonb),
  ('10090860', 'Infero Occurrence', 11.067220, 48.567690, 'occurrence', 'Iron', array['Iron'], null, array['Marble'], 'GREENWOOD, J.E-G.W., 1960, GEOLOGY OF THE LAS KHOREH=ELAYU AREA, ERIGAVO DISTRICT: SOMALILAND BRITISH GEOLOGICAL SURVEY REPORT NO. 3, 36P', '{"mrds_id":"D007077","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090860"}'::jsonb),
  ('10090861', 'Dala Ad Occurrence', 9.967340, 44.667760, 'occurrence', 'Asbestos', array['Asbestos'], null, '{}'::text[], 'HUNT, J.A., 1958, GEOLOGY OF THE ADADLEH AREA, HARGEISA AND BERBERA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 2, 16 P', '{"mrds_id":"D007080","dev_stat":"Occurrence","ore":"Chrysotile","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10090861"}'::jsonb),
  ('10094415', 'Buhl Prospect', 10.750600, 43.467780, 'occurrence', 'Molybdenum', array['Molybdenum','Lead','Bismuth'], null, array['Gabbro','Schist','Gneiss','Granite'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY-SOMALIA: UNITED NATIONS REPORT, 133 P.DANIELS, J.L., MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND (BRITISH) PROTECTORATE DEPT OF GEOLOGICAL SURVEY MINERAL RESOU', '{"mrds_id":"D006908","dev_stat":"Occurrence","ore":"Anthophyllite, Bismuthinite, Chalcopyrite, Galena, Garnet, Molybdenite","structure":"N 75 To 100 E","prod_size":"N","commod3":"Copper, Asbestos, Garnet","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094415"}'::jsonb),
  ('10094416', 'Bender Ziada Prospect', 11.243320, 48.976850, 'occurrence', null, '{}'::text[], null, array['Gravel'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006911","dev_stat":"Occurrence","ore":"Cassiterite","prod_size":"N","commod3":"Tin","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094416"}'::jsonb),
  ('10094418', 'Hammas Prospect', 10.100660, 44.834420, 'occurrence', null, '{}'::text[], null, array['Gneiss'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY-SOMALIA: UNITED NATIONS REPORT, 133 P', '{"mrds_id":"D006919","dev_stat":"Occurrence","ore":"Cassiterite, Quartz","prod_size":"N","commod3":"Quartz, Tin","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094418"}'::jsonb),
  ('10094419', 'Qabri Bahir', 10.317310, 43.801100, 'occurrence', null, '{}'::text[], null, array['Gneiss'], 'DANIELS, J.L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P.CLYNE, W., 1959, REPORT ON THE BERYL RESOURCES OF SOMALILAND PROTECTORATE: SOMALILAND BRITI', '{"mrds_id":"D006922","dev_stat":"Occurrence","ore":"Beryl, Columbite","prod_size":"N","commod3":"Niobium (Columbium), Beryllium","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094419"}'::jsonb),
  ('10094420', 'Maag Prospect', 11.117220, 48.751020, 'occurrence', null, '{}'::text[], null, array['Schist'], 'HUNT, J.A., 1951, A GENERAL SURVEY OF THE SOMALILAND PROTECTORATE 1944-1950: CROWN AGENTS, LONDON, 203 P', '{"mrds_id":"D006934","dev_stat":"Occurrence","ore":"Barite, Galena","tectonic":"Margin Gulf Of Aden Spreading Center","prod_size":"N","commod3":"Lead, Barium-Barite","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094420"}'::jsonb),
  ('10094421', 'Sheikh Prospect', 9.934000, 45.201080, 'occurrence', null, '{}'::text[], null, array['Schist'], 'HUNG, J.A., 1951, A GENERAL SURVEY OF THE SOMALILAND PROTECTORATE 1944-1950: CROWN AGENTS, LONDON, 203 P', '{"mrds_id":"D006937","dev_stat":"Occurrence","ore":"Garnet","prod_size":"N","commod3":"Garnet","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094421"}'::jsonb),
  ('10094422', 'Bihen Gaha Prospect', 10.417290, 45.651070, 'occurrence', 'Manganese', array['Manganese'], null, array['Limestone'], 'FARQUHARSON, M.A., 1924, FIRST REPORT ON THE GEOLOGY AND MINERAL RESOURCES OF BRITISH SOMALILAND: WATERLOW AND SONS LTD., LONDON, 53 P', '{"mrds_id":"D006940","dev_stat":"Occurrence","tectonic":"Margin Gulf Of Aden Spreading Center","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094422"}'::jsonb),
  ('10094423', 'Bihendula Prospect', 10.167320, 45.134410, 'occurrence', null, '{}'::text[], null, '{}'::text[], 'HUNT, J. A., 1951, A GENERAL SURVEY OF THE SOMALILAND PROTECTORATE 1944-1950: CROWN AGENTS, LONDON, 203 P', '{"mrds_id":"D006945","dev_stat":"Occurrence","ore":"Limestone","prod_size":"N","commod3":"Cement Rock","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094423"}'::jsonb),
  ('10094424', 'Bur Galangol Occurrence', 2.284710, 43.501090, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006979","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094424"}'::jsonb),
  ('10094425', 'Bur Battei Occurrence', 2.434700, 43.134430, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006982","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094425"}'::jsonb),
  ('10094426', 'Bur Arare Occurrence', 2.551360, 43.151100, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006985","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094426"}'::jsonb),
  ('10094427', 'Bur Dibdividen Occurrence', 2.134730, 43.134430, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R.J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006988","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094427"}'::jsonb),
  ('10094428', 'Bur Gardascia Occurrence', 2.268050, 43.384420, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R. J., 19548 A RECONNAISSANCE SURVEY OF THE MINERALDEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): U.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006991","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094428"}'::jsonb),
  ('10094429', 'Bur Dur Occurrence', 2.518030, 43.517760, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R. J., 1954, A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): US.S. TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006994","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094429"}'::jsonb),
  ('10094430', 'Bur Jocoe Occurrence', 2.784660, 44.484410, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'HOLMES, R. J., 1954 A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): US.S TECHNICAL ASSISTEANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D006997","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094430"}'::jsonb),
  ('10094431', 'Girta Gabno Occurrence', 5.134450, 45.434390, 'occurrence', 'Iron', array['Iron'], null, array['Sandstone'], 'HOLMES, R. J., 19548 A RECONNAISSANCE SURVEY OF THE MINERAL DEPOSITS OF SOMALIA (FORMER ITALIAN SOMALILAND): US.S TECHNICAL ASSISTANCE MISSION (T.A. 45-125) REPORT, 83 P', '{"mrds_id":"D007002","dev_stat":"Occurrence","ore":"Hematite","hrock_unit":"Jesomma Sandstone","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094431"}'::jsonb),
  ('10094432', 'Bustanka Prospect', 10.100660, 45.034410, 'occurrence', 'Lead', array['Lead','Barium-Barite','Fluorine-Fluorite'], null, array['Migmatite'], 'HUNT, J. A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007010","dev_stat":"Occurrence","ore":"Barite, Fluorite, Galena","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094432"}'::jsonb),
  ('10094433', 'Daba Shabeli Occurrence', 10.150650, 45.417750, 'occurrence', 'Iron', array['Iron'], null, array['Ultramafic Intrusive Rock'], 'HUNT, J. A., 1960, GEOLOGY OF THE BERBERA - SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT NO. 4, 27 P', '{"mrds_id":"D007015","dev_stat":"Occurrence","ore":"Chromite, Magnetite","prod_size":"N","commod2":"Chromium, Nickel","commod3":"Platinum","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094433"}'::jsonb),
  ('10094434', 'Gabile Well Occurrence', 10.167330, 43.217780, 'occurrence', 'Strontium', array['Strontium'], null, array['Shale'], 'FARQUHARSON, M. A., 1924, FIRST REPORT ON THE GEOLOGY AND MINERAL RESOURCES OF BRITISH SOMALILAND: WATERLOW AND SONS LTD., LONDON, 53 P', '{"mrds_id":"D007042","dev_stat":"Occurrence","hrock_unit":"Anhydrite Series","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094434"}'::jsonb),
  ('10094435', 'Darkainle Prospect', 10.383970, 43.267780, 'occurrence', 'Molybdenum', array['Molybdenum'], null, array['Nepheline Syenite'], 'DANIELS, J. L., 1960, MINERALS AND ROCKS OF HARGEISA AND BORAMA DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY MINERAL RESOURCES PAMPHLET NO. 3, 25 P', '{"mrds_id":"D007048","dev_stat":"Occurrence","ore":"Chalcopyrite, Ferrimolybdite, Molybdenite, Pyrochlore, Sphalerite","prod_size":"N","commod2":"Uranium, Copper, Zinc","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094435"}'::jsonb),
  ('10094436', 'Qadia Occurrence', 2.818000, 43.334430, 'occurrence', 'Iron', array['Iron'], null, array['Quartzite'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133P', '{"mrds_id":"D007076","dev_stat":"Occurrence","ore":"Hematite, Magnetite","prod_size":"N","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10094436"}'::jsonb),
  ('10096851', 'Suria Malableh', 10.350630, 45.117750, 'prospect', 'Gypsum-Anhydrite', array['Gypsum-Anhydrite'], 'Sedimentary', array['Limestone'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY-SOMALIA: UNITED NATIONS REPORT, 133PHUNT, J. A., 1960, GEOLOGY OF THE BERBERA-SHEIKH AREA, BERBERA AND BURAO DISTRICTS: SOMALILAND BRITISH PROTECTORATE GEOLOGICAL SURVEY REPORT N', '{"mrds_id":"D006923","dev_stat":"Prospect","ore":"Celestite, Gypsum","hrock_unit":"Anhydrite","prod_size":"N","commod2":"Strontium","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10096851"}'::jsonb),
  ('10096852', 'Alio Ghelle Prospect', 2.484690, 43.667760, 'prospect', 'Thorium', array['Thorium'], 'Contact Metasomatic', array['Gneiss'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY-SOMALIA: UNITED NATIONS REPORT, 133 P', '{"mrds_id":"D006998","dev_stat":"Prospect","ore":"Coffinite, Pitchblende, Thorite","gangue":"Barite, Chalcopyrite, Galena, Pyrite, Sphene","prod_size":"N","commod2":"Uranium","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10096852"}'::jsonb),
  ('10096853', 'Unnamed Radioactivity Anomaly', 2.668020, 43.217770, 'prospect', null, '{}'::text[], 'Contact Metasomatic', array['Quartzite'], 'UNITED NATIONS DEVELOPMENT PROGRAMME, 1970, MINERAL AND GROUNDWATER SURVEY - SOMALIA: UNITED NATIONS REPORT, 133', '{"mrds_id":"D007005","dev_stat":"Prospect","prod_size":"N","commod3":"Thorium, Uranium","url":"https://mrdata.usgs.gov/mrds/show-mrds.php?dep_id=10096853"}'::jsonb)
) as v(external_id, name, lat, lng, status, commodity_key, commodities, deposit_type, host_rocks, reference, metadata),
  geo.dataset_registry d
  join geo.knowledge_source ks on ks.dataset_id = d.id
where d.source_key = 'usgs_mrds' and d.version = '2026.07'
  and not exists (select 1 from geo.mineral_occurrence mo
                  where mo.dataset_id = d.id and mo.external_id = v.external_id);

-- ── VERIFY ── expect 159 occurrences for this dataset ──
--   select count(*) from geo.mineral_occurrence o join geo.dataset_registry d on d.id=o.dataset_id
--     where d.source_key='usgs_mrds';
--   -- a Somalia point should find neighbours:
--   select name, commodity_key, round(distance_m) m from geo.occurrences_near(2.04, 45.34, 50000) limit 5;

-- ── ROLLBACK ──
--   delete from geo.dataset_registry where source_key='usgs_mrds';  -- cascades occurrences + source
