-- 0086_commodity_profile.sql
--
-- Economic Mineral Intelligence Engine (EMIE) — the commodity knowledge base.
-- One row per economically important commodity: its typical geological setting plus
-- its STRATEGIC / INDUSTRIAL importance (never price). This feeds the Geological
-- Knowledge Provider so the AI can teach WHY a rock/environment matters, not just
-- name it. Read-only knowledge (no location); seeded here, curated over time.
--
-- Style rule: strategic_importance / industrial_uses are written in a teaching
-- voice; confidence_limitations is framed as "what to confirm next", never a legal
-- disclaimer. Knowledge is weak evidence downstream (tier knowledge_kb) — it enriches
-- reasoning but can never, on its own, produce high confidence.

create table if not exists geo.commodity_profile (
  code                   text primary key,
  name                   text not null,
  category               text not null,   -- precious_metal|battery|critical|gemstone|base_metal|industrial|energy
  typical_host_rocks     text[] not null default '{}',
  associated_minerals    text[] not null default '{}',
  alteration_styles      text[] not null default '{}',
  deposit_models         text[] not null default '{}',
  tectonic_settings      text[] not null default '{}',
  exploration_indicators text[] not null default '{}',
  industrial_uses        text[] not null default '{}',
  is_critical_mineral    boolean not null default false,
  strategic_importance   text,
  confidence_limitations text not null,
  citations              jsonb not null default '[]'::jsonb,  -- 'references' is a reserved word
  created_at             timestamptz not null default now()
);

alter table geo.commodity_profile enable row level security;
-- Knowledge is read through security-definer RPCs; no client policy needed. Service
-- role (engine) may read directly.
grant select on geo.commodity_profile to service_role;

-- ── SEED ────────────────────────────────────────────────────────────────────
insert into geo.commodity_profile
  (code, name, category, typical_host_rocks, associated_minerals, alteration_styles,
   deposit_models, tectonic_settings, exploration_indicators, industrial_uses,
   is_critical_mineral, strategic_importance, confidence_limitations) values

('gold','Gold','precious_metal',
 '{quartz vein,greywacke,banded iron formation,felsic intrusive,shear zone}',
 '{pyrite,arsenopyrite,quartz,chalcopyrite,galena,tellurides}',
 '{silicification,sericitic,carbonatization,iron staining}',
 '{orogenic gold,epithermal,porphyry,placer,BIF-hosted}',
 '{greenstone belt,accretionary orogen,volcanic arc}',
 '{quartz veins in shear zones,sulphide veinlets,gossan/iron staining,visible gold}',
 '{electronics,jewellery,dentistry,aerospace contacts}',
 false,
 'Gold is prized for its conductivity and corrosion resistance in electronics and aerospace as well as its use as a store of value; explorers chase it in quartz-vein and shear-hosted systems worldwide.',
 'Quartz veins and iron staining are encouraging but not proof of gold; the next field step is to look for sulphides (pyrite, arsenopyrite) and to sample fresh vein material for assay.'),

('silver','Silver','precious_metal',
 '{felsic volcanic,quartz vein,carbonate}',
 '{galena,sphalerite,argentite,tetrahedrite,pyrite}',
 '{silicification,argillic,sericitic}',
 '{epithermal,VMS,polymetallic vein}',
 '{volcanic arc,rift}',
 '{banded quartz-adularia veins,base-metal sulphides,vuggy silica}',
 '{electronics,solar photovoltaics,batteries,antibacterial coatings}',
 false,
 'Silver is the best electrical conductor of all metals and is central to solar panels and electronics; it commonly travels with lead and zinc in epithermal and volcanogenic systems.',
 'Silver is usually confirmed by assay of sulphide-bearing veins rather than by eye; look for galena and sphalerite alongside it.'),

('pgm','Platinum Group Metals','precious_metal',
 '{layered mafic intrusion,chromitite,dunite,pyroxenite}',
 '{chromite,pentlandite,pyrrhotite,chalcopyrite,olivine}',
 '{serpentinization}',
 '{layered intrusion reef,Ni-Cu-PGE sulphide,placer}',
 '{craton,large igneous province}',
 '{chromitite layers,mafic-ultramafic layering,Ni-Cu sulphide}',
 '{catalytic converters,hydrogen fuel cells,electronics,chemical catalysts}',
 true,
 'Platinum, palladium and rhodium are critical catalysts for clean-air technology and hydrogen fuel cells; they concentrate in layered mafic-ultramafic intrusions.',
 'PGM grades are invisible in hand specimen and need assay; the geological signal is the mafic-ultramafic host and chromitite layering.'),

('lithium','Lithium','battery',
 '{pegmatite,granite,evaporite,claystone}',
 '{spodumene,lepidolite,petalite,tourmaline,albite,quartz}',
 '{greisenization,albitization}',
 '{LCT pegmatite,continental brine,lithium clay}',
 '{craton margin,collisional orogen}',
 '{zoned pegmatites,spodumene crystals,lepidolite,Li-rich brines}',
 '{EV batteries,grid energy storage,ceramics,glass}',
 true,
 'Lithium is the backbone of electric-vehicle batteries and grid storage; explorers target lithium-rich (LCT) pegmatites and salar brines.',
 'Confirming lithium means identifying spodumene/lepidolite and assaying; a plain granite or pegmatite is only a starting point.'),

('nickel','Nickel','battery',
 '{komatiite,dunite,serpentinite,laterite,gabbro}',
 '{pentlandite,pyrrhotite,chromite,millerite,garnierite}',
 '{serpentinization,lateritic weathering}',
 '{magmatic Ni-Cu sulphide,Ni laterite}',
 '{craton,ophiolite,large igneous province}',
 '{ultramafic rocks,massive/disseminated sulphide,green garnierite in laterite}',
 '{stainless steel,EV batteries,superalloys}',
 true,
 'Nickel gives stainless steel its strength and is a key cathode metal in EV batteries; it forms in ultramafic magmatic sulphide systems and in tropical laterites over ultramafic rock.',
 'Nickel in ultramafic rock is common at trace levels; an economic target needs sulphide accumulation or lateritic enrichment, confirmed by assay.'),

('cobalt','Cobalt','battery',
 '{sediment-hosted copper,ultramafic,laterite}',
 '{cobaltite,pentlandite,erythrite,carrollite}',
 '{lateritic weathering}',
 '{sediment-hosted Cu-Co,magmatic sulphide,Ni-Co laterite}',
 '{intracontinental rift,craton}',
 '{pink erythrite bloom,Cu-Co sulphides,ultramafic laterite}',
 '{EV batteries,superalloys,magnets}',
 true,
 'Cobalt stabilises EV battery cathodes and hardens aerospace superalloys; it rides along with copper in sediment-hosted systems and with nickel in laterites.',
 'Cobalt rarely forms its own ore; look for it with copper or nickel, and confirm by assay.'),

('graphite','Graphite','battery',
 '{marble,paragneiss,schist}',
 '{graphite,pyrite,calcite,mica}',
 '{high-grade metamorphism}',
 '{flake graphite in metamorphic rock,vein graphite}',
 '{high-grade metamorphic belt}',
 '{graphitic schist/gneiss,shiny grey flakes,conductive rock}',
 '{EV battery anodes,refractories,lubricants,electrodes}',
 true,
 'Graphite is the main anode material in lithium-ion batteries and a key refractory; the best flake deposits sit in high-grade metamorphic rocks.',
 'A grey shiny rock may be graphite or molybdenite/sulphide; a streak and flake test plus assay confirm grade.'),

('manganese','Manganese','battery',
 '{sedimentary,chert,banded iron formation}',
 '{pyrolusite,rhodochrosite,braunite}',
 '{supergene enrichment}',
 '{sedimentary Mn,supergene}',
 '{passive margin,rift}',
 '{black manganese oxides,Mn-rich sediment}',
 '{steel alloying,EV batteries,dry-cell batteries}',
 true,
 'Manganese is essential to steelmaking and increasingly to battery cathodes; it accumulates in marine sediments and supergene blankets.',
 'Black coatings can be manganese or other oxides; confirm with assay.'),

('ree','Rare Earth Elements','critical',
 '{carbonatite,alkaline intrusion,laterite,placer}',
 '{bastnaesite,monazite,xenotime,apatite,fluorite}',
 '{fenitization}',
 '{carbonatite,ion-adsorption clay,placer monazite}',
 '{intracontinental rift,craton}',
 '{carbonatite/alkaline complex,radioactive heavy minerals,fenite aureole}',
 '{permanent magnets,wind turbines,EV motors,electronics,defence}',
 true,
 'Rare earths power the permanent magnets in wind turbines and EV motors and are strategic for defence and electronics; carbonatites and ion-adsorption clays are the main sources.',
 'REE minerals are often radioactive and fine-grained; a scintillometer reading and mineralogical/assay work are the real confirmation.'),

('tantalum','Tantalum','critical',
 '{pegmatite,granite}',
 '{tantalite,columbite,cassiterite,spodumene,beryl}',
 '{greisenization,albitization}',
 '{LCT pegmatite,rare-metal granite}',
 '{craton margin}',
 '{zoned pegmatites,dark heavy columbite-tantalite,associated Sn/Li}',
 '{capacitors,electronics,medical implants,aerospace}',
 true,
 'Tantalum makes the tiny high-performance capacitors in phones and computers and is used in medical and aerospace alloys; it occurs with lithium and tin in evolved pegmatites.',
 'Columbite-tantalite is dense and dark but needs assay to separate Ta from Nb; the pegmatite context is the first clue.'),

('niobium','Niobium','critical',
 '{carbonatite,alkaline intrusion,pegmatite}',
 '{pyrochlore,columbite,apatite}',
 '{fenitization}',
 '{carbonatite,rare-metal pegmatite}',
 '{intracontinental rift}',
 '{carbonatite complex,pyrochlore,fenite}',
 '{high-strength steel,superalloys,superconductors}',
 true,
 'Niobium micro-alloys strengthen the steel in pipelines and cars and enables superconductors; carbonatites are its dominant source.',
 'Niobium tracks with REE in carbonatites; mineral identification and assay confirm it.'),

('tungsten','Tungsten','critical',
 '{skarn,greisen,quartz vein,granite}',
 '{scheelite,wolframite,cassiterite,molybdenite,quartz}',
 '{greisenization,skarn (calc-silicate)}',
 '{skarn,greisen,vein}',
 '{collisional orogen,continental arc}',
 '{scheelite fluorescing blue under UV,wolframite in veins,granite contact skarn}',
 '{cutting tools,carbide drill bits,alloys,electronics}',
 true,
 'Tungsten gives cutting tools and drill bits their hardness and heat resistance; it concentrates in skarns and greisens around granites.',
 'Scheelite fluoresces blue under UV — a great field test — but grade still needs assay.'),

('tin','Tin','critical',
 '{granite,greisen,pegmatite,placer}',
 '{cassiterite,wolframite,tourmaline,topaz,quartz}',
 '{greisenization,tourmalinization}',
 '{greisen,vein,placer cassiterite}',
 '{collisional orogen}',
 '{cassiterite (heavy dark tin oxide),greisen,tourmaline-rich granite}',
 '{solder,tinplate,alloys,electronics}',
 true,
 'Tin is the solder that joins virtually all electronics and coats steel cans; it comes from cassiterite in evolved granites, greisens and downstream placers.',
 'Cassiterite is heavy and can be panned, but confirm with assay; a plain granite is not yet a tin deposit.'),

('copper','Copper','base_metal',
 '{porphyry intrusive,basalt,sediment-hosted,VMS}',
 '{chalcopyrite,bornite,malachite,azurite,pyrite}',
 '{potassic,phyllic,argillic,propylitic}',
 '{porphyry copper,sediment-hosted Cu,VMS,skarn}',
 '{continental arc,rift}',
 '{green malachite/blue azurite staining,chalcopyrite,alteration zoning}',
 '{electrical wiring,motors,renewable energy,EV,construction}',
 false,
 'Copper is the metal of electrification — wiring, motors, renewables and EVs all depend on it; it forms giant porphyry systems and sediment-hosted belts.',
 'Green/blue copper staining is a strong indicator; map the alteration zoning and assay to gauge a system.'),

('uranium','Uranium','energy',
 '{sandstone,granite,unconformity,black shale}',
 '{uraninite,pitchblende,coffinite,carnotite}',
 '{hematitization,argillic}',
 '{unconformity-related,sandstone-hosted,IOCG}',
 '{craton,intracontinental basin}',
 '{radiometric anomaly,yellow secondary U minerals,redox fronts}',
 '{nuclear power,medical isotopes}',
 true,
 'Uranium fuels low-carbon nuclear power and medical isotopes; it concentrates at redox fronts in sandstones and at basement unconformities.',
 'Uranium is found with a scintillometer, not the eye; radioactivity plus assay confirm it, and handling needs care.'),

('vanadium','Vanadium','critical',
 '{layered mafic intrusion,titaniferous magnetite,black shale}',
 '{magnetite,vanadinite,titanomagnetite}',
 '{}',
 '{magmatic V-Ti magnetite,shale-hosted}',
 '{large igneous province}',
 '{titaniferous magnetite layers in mafic rock}',
 '{steel alloying,vanadium redox-flow batteries,aerospace}',
 true,
 'Vanadium strengthens steel and powers grid-scale redox-flow batteries; it rides in titaniferous magnetite of layered mafic intrusions.',
 'Vanadium is locked in magnetite and needs assay; the mafic-intrusion host is the geological cue.'),

('beryllium','Beryllium','critical',
 '{pegmatite,greisen,rhyolite}',
 '{beryl,bertrandite,quartz,muscovite}',
 '{greisenization}',
 '{LCT pegmatite,volcanogenic Be}',
 '{craton margin}',
 '{beryl crystals (aquamarine/emerald),rare-metal pegmatite}',
 '{aerospace alloys,electronics,X-ray windows,defence}',
 true,
 'Beryllium makes ultra-light stiff alloys for aerospace and precision electronics; it occurs as beryl in pegmatites and greisens.',
 'Green/blue beryl is a visible clue, but Be grade needs assay; most beryl is not gem-quality.'),

('iron','Iron','industrial',
 '{banded iron formation,skarn,magmatic}',
 '{hematite,magnetite,goethite}',
 '{supergene enrichment}',
 '{BIF-hosted,magmatic magnetite,skarn}',
 '{craton,passive margin}',
 '{banded iron formation,magnetic rock,red/grey iron oxides}',
 '{steelmaking,construction,heavy industry}',
 false,
 'Iron is the foundation of steel and modern construction; the great deposits are banded iron formations enriched by weathering.',
 'Banded iron formation is diagnostic in outcrop; grade depends on hematite/magnetite enrichment, confirmed by assay.'),

('diamond','Diamond','gemstone',
 '{kimberlite,lamproite,placer}',
 '{pyrope garnet,chrome diopside,chromite,ilmenite,olivine}',
 '{serpentinization}',
 '{kimberlite pipe,lamproite,alluvial placer}',
 '{craton,stable Precambrian basement}',
 '{kimberlite pipe/dyke,mantle indicator minerals,pyrope garnet,chrome diopside}',
 '{gemstones,industrial cutting/drilling,abrasives}',
 false,
 'Diamond is both the ultimate gemstone and a critical industrial abrasive; nearly all natural diamond is delivered to surface by kimberlite from the deep mantle beneath old cratons.',
 'Not every kimberlite is diamond-bearing — only a small fraction of pipes are economic; the productive next step is to search for indicator minerals (pyrope garnet, chrome diopside) and pipe morphology.'),

('emerald','Emerald','gemstone',
 '{schist,pegmatite,black shale,hydrothermal vein}',
 '{beryl,quartz,pyrite,mica,tourmaline}',
 '{biotitization,albitization}',
 '{schist-hosted emerald,pegmatite-related,vein-hosted}',
 '{collisional orogen}',
 '{beryl in mica schist near pegmatite,Cr/V-bearing host}',
 '{gemstones,jewellery}',
 false,
 'Emerald is green beryl coloured by chromium or vanadium and one of the most valued gems; it forms where beryllium-rich fluids meet chromium-bearing host rocks.',
 'Green colour alone is not emerald; clarity, colour and origin need gemological testing.'),

('corundum','Ruby & Sapphire','gemstone',
 '{marble,gneiss,basalt,pegmatite,placer}',
 '{corundum,spinel,mica,garnet}',
 '{contact metamorphism,desilication}',
 '{marble-hosted ruby,basalt-hosted sapphire,placer}',
 '{collisional orogen,intraplate volcanic}',
 '{corundum crystals in marble or alkali basalt,alluvial gem gravels}',
 '{gemstones,watch bearings,abrasives,laser optics}',
 false,
 'Ruby and sapphire are gem varieties of corundum (aluminium oxide), second only to diamond in hardness and used in optics and bearings as well as jewellery; they form in marbles and alkali basalts.',
 'Red/blue crystals may be corundum or garnet/spinel; hardness and gemological testing confirm identity and quality.'),

('tourmaline','Tourmaline','gemstone',
 '{pegmatite,granite,greisen,schist}',
 '{tourmaline,quartz,feldspar,lepidolite,beryl}',
 '{tourmalinization,greisenization}',
 '{LCT pegmatite,greisen}',
 '{craton margin,collisional orogen}',
 '{black/coloured tourmaline crystals in pegmatite,tourmalinized granite}',
 '{gemstones,piezoelectric sensors}',
 false,
 'Tourmaline is both a gemstone family and a piezoelectric mineral; its presence flags evolved pegmatite/greisen systems that may also carry lithium, tin and tantalum.',
 'Coloured (gem) tourmaline is rare; most is black schorl — a useful exploration indicator rather than a gem in itself.');

-- ── VERIFY ── expect ~24 commodity rows ─────────────────────────────────────
--   select count(*) from geo.commodity_profile;  -- ~24

-- ── ROLLBACK ──
--   drop table if exists geo.commodity_profile;
