// The generate/share path calls native modules; stub them so importing the
// module (for the pure HTML builder) never touches native code.
jest.mock("expo-print", () => ({ printToFileAsync: jest.fn() }));
jest.mock("expo-sharing", () => ({ isAvailableAsync: jest.fn(), shareAsync: jest.fn() }));
jest.mock("expo-file-system", () => ({ cacheDirectory: "", copyAsync: jest.fn() }));

import { buildGoldProspectHtml, type GoldProspectPdfData } from "./goldProspectPdfReport";

const base: GoldProspectPdfData = {
  scanId: "abcd1234ef",
  createdAt: "2026-01-05T10:00:00.000Z",
  hostRock: "Quartz vein",
  hostConfidencePct: 82,
  environment: "Hydrothermal quartz vein — a common lode-gold structure.",
  score: 64,
  categoryLabel: "High",
  economicLabel: "Promising exploration target",
  categoryColor: "#2E9E4F",
  evidenceFor: ["Host rock is commonly associated with gold.", "Quartz veins were observed."],
  evidenceAgainst: ["No sulfide minerals were observed."],
  nextSteps: ["Collect additional samples.", "Sweep the area with a metal detector."],
  regionalGeology: { line: "Within a documented gold province.", source: "USGS", favorable: true },
  location: { lat: 10.5, lng: 47.0, label: "Sanaag, Somalia" },
};

describe("buildGoldProspectHtml", () => {
  const html = buildGoldProspectHtml(base, "en");

  it("carries LuulScan Lab Company branding, not GemScan", () => {
    expect(html).toContain("LuulScan Lab Company");
    expect(html).toMatch(/Generated by LuulScan Lab Company/);
    expect(html).not.toMatch(/GemScan/);
  });

  it("is a rule-based Geological Prospect Assessment, never labeled AI", () => {
    expect(html).toMatch(/Geological Prospect Assessment/);
    expect(html).not.toMatch(/\bAI\b/);
  });

  it("includes every required section and identifier", () => {
    expect(html).toContain("Quartz vein"); // detected host rock
    expect(html).toContain("64"); // score
    expect(html).toContain("High"); // category
    expect(html).toContain("Promising exploration target"); // economic
    expect(html).toMatch(/Evidence Supporting/);
    expect(html).toMatch(/Evidence Against/);
    expect(html).toMatch(/Regional Geology/);
    expect(html).toMatch(/Recommended Next Steps/);
    expect(html).toMatch(/GP-ABCD1234/); // prospect evaluation id
    expect(html).toMatch(/ABCD1234/); // report id
  });

  it("renders the location/map section only when a location is present", () => {
    expect(html).toContain("47.00000");
    const noLoc = buildGoldProspectHtml({ ...base, location: null }, "en");
    expect(noLoc).not.toContain("47.00000");
  });

  it("renders in Somali too", () => {
    const so = buildGoldProspectHtml(base, "so");
    expect(so).toMatch(/Warbixinta Rajada Dahabka|Qiimaynta Rajada/);
    expect(so).toContain("LuulScan Lab Company");
  });
});
